import { expect, test } from './account-fixtures.ts'
import { getRoomComponents } from '../../shared/roomComponents.ts'
import { chooseOption, openRoomObjects } from './fixtures.ts'

test.use({ providerEnabled: false, reducedMotion: 'reduce' })

test('one plant menu item exposes both positions and moves the chosen plant in a private live preview', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/kitchen')
  const objects = await openRoomObjects(page)
  const plants = objects.getByRole('button', { name: 'Open Plant details', exact: true })
  await expect(plants).toHaveCount(1)
  await expect(plants).toContainText('2 positions')
  await plants.click()
  const positions = objects.getByRole('group', { name: 'Plant positions', exact: true })
  await expect(positions.getByRole('button')).toHaveCount(2)
  await positions.getByRole('button', { name: 'Counter planter', exact: true }).click()
  await objects.getByRole('button', { name: 'Edit this object', exact: true }).click()
  const editor = page.locator('.room-editor')
  await expect(editor.getByRole('combobox', { name: 'Position', exact: true })).toHaveAttribute('data-value', 'kitchen-plant-counter')
  await expect(editor.getByText('Original', { exact: true })).toHaveCount(0)
  await expect(editor.getByRole('combobox', { name: 'Finish', exact: true })).toContainText('Match room colors')
  await chooseOption(editor.getByRole('combobox', { name: 'Position', exact: true }), 'kitchen-windowsill')
  const world = page.locator('.kitchen-world')
  await expect(world).toHaveAttribute('data-selected-component', 'default-kitchen-plant-counter')
  await expect(world.locator('[data-component-id="default-kitchen-plant-counter"] .hotspot-label')).toHaveText('Plant, Window ledge')
  const before = await accounts.store.get(owner.household.id)
  expect(getRoomComponents(before ?? {}).find((component) => component.id === 'default-kitchen-plant-counter')?.slotId).toBe('kitchen-plant-counter')
  await editor.getByRole('button', { name: 'Apply for everyone', exact: true }).click()
  await expect(editor).toHaveCount(0)
  const saved = await accounts.store.get(owner.household.id)
  expect(getRoomComponents(saved ?? {}).find((component) => component.id === 'default-kitchen-plant-counter')?.slotId).toBe('kitchen-windowsill')
  await openRoomObjects(page)
  await expect(plants).toHaveCount(1)
  await expect(plants).toContainText('2 positions')
})

test('additional placements stay grouped and cancel restores the saved positions', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await page.goto('/kitchen')
  const objects = await openRoomObjects(page)
  await objects.getByRole('button', { name: 'Open Plant details', exact: true }).click()
  await objects.getByRole('button', { name: 'Edit this object', exact: true }).click()
  const editor = page.locator('.room-editor')
  await editor.getByRole('button', { name: 'Add at another position', exact: true }).click()
  await editor.getByRole('button', { name: 'Place object', exact: true }).click()
  await expect(editor.getByRole('group', { name: 'Plant positions', exact: true }).getByRole('button')).toHaveCount(3)
  await editor.getByRole('button', { name: 'All room objects', exact: true }).click()
  const plantCard = editor.getByRole('button', { name: 'Edit Plant', exact: true })
  await expect(plantCard).toHaveCount(1)
  await expect(plantCard).toContainText('3 positions')
  await expect(plantCard).toContainText('In preview')
  await editor.getByRole('button', { name: 'Cancel', exact: true }).click()
  expect((await accounts.store.get(owner.household.id))?.roomComponents).toEqual(owner.household.roomComponents)
})
