import { expect, test } from '@playwright/test'

test('fridge, expenses, repayment records, and reload persistence', async ({ page }) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Make yourself at home.' })).toBeVisible()
  await expect(page.locator('.world-canvas canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Close the fridge' }).click()
  await expect(page.getByRole('button', { name: 'Peek inside' })).toBeVisible()
  await page.getByRole('button', { name: 'Peek inside' }).click()
  await page.getByRole('button', { name: 'Stock the fridge, add a grocery run', exact: true }).click()
  await page.getByLabel('What did you pick up?').fill('Browser test tomatoes')
  await page.getByLabel('Total (EUR)').fill('12.03')
  await page.getByRole('button', { name: 'Add & split the groceries' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.getByText('Browser test tomatoes', { exact: true })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.getByText('Browser test tomatoes', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.getByRole('button', { name: 'Settle up', exact: true }).first().click()
  await page.getByRole('button', { name: 'Record paid', exact: true }).first().click()
  await expect(page.getByRole('dialog')).toContainText('does not move money')
  await page.getByRole('button', { name: 'Yes, record payment' }).click()
  await expect(page.locator('.history-row')).toHaveCount(1)
  await page.getByRole('button', { name: 'Undo', exact: true }).click()
  await page.getByRole('button', { name: 'Undo payment record' }).click()
  await expect(page.locator('.history-row')).toHaveCount(0)
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await page.getByRole('button', { name: 'Remove Browser test tomatoes', exact: true }).click()
  await page.getByRole('button', { name: 'Remove grocery run', exact: true }).click()
  await expect(page.getByText('Browser test tomatoes', { exact: true })).toHaveCount(0)
  expect(pageErrors).toEqual([])
})

test('a new kitchen can be joined from a separate browser session', async ({ page, browser }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Make it yours' }).click()
  await page.getByLabel('What do you call home?').fill('The browser house')
  await page.getByLabel('Your name', { exact: true }).fill('Charlie')
  await page.getByRole('button', { name: 'Create our kitchen' }).click()
  await expect(page.locator('.game-demo')).toHaveCount(0)
  await page.getByRole('button', { name: 'Invite a roommate', exact: false }).first().click()
  const invitation = await page.getByLabel('Your private kitchen invitation').inputValue()
  const context = await browser.newContext()
  const roommate = await context.newPage()
  await roommate.goto(invitation)
  await roommate.getByLabel('Your name', { exact: true }).fill('Dana')
  await roommate.getByRole('button', { name: 'Join the kitchen', exact: true }).click()
  await expect(roommate.locator('.game-house')).toContainText('The browser house')
  await roommate.getByRole('button', { name: 'Stock the fridge, add a grocery run', exact: true }).click()
  await roommate.getByLabel('What did you pick up?').fill('Shared groceries')
  await roommate.getByLabel('Total (EUR)').fill('10')
  await roommate.getByRole('button', { name: 'Add & split the groceries' }).click()
  await page.reload()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.getByText('Shared groceries', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.getByRole('button', { name: 'The roommates', exact: true }).click()
  await page.getByRole('button', { name: 'The Sunday House Return as You' }).click()
  await expect(page.locator('.game-demo')).toBeVisible()
  await page.getByRole('button', { name: 'The roommates', exact: true }).click()
  await page.getByRole('button', { name: 'The browser house Return as Charlie' }).click()
  await expect(page.locator('.player-button')).toHaveAttribute('aria-label', 'The roommates, playing as Charlie')
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.getByText('Shared groceries', { exact: true })).toBeVisible()
  await context.close()
})

test('mobile layout has no horizontal overflow and supports keyboard dialogs', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Make yourself at home.' })).toBeVisible()
  await expect(page.locator('.world-canvas canvas')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Stock the fridge, add a grocery run', exact: true }).click()
  await expect(page.getByLabel('What did you pick up?')).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('a rejected save keeps the expense draft available to retry', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Stock the fridge, add a grocery run', exact: true }).click()
  await page.getByLabel('What did you pick up?').fill('Keep this grocery draft')
  await page.getByLabel('Total (EUR)').fill('4.20')
  await page.route('**/api/expenses', async (route) => {
    await route.fulfill({ status: 409, contentType: 'application/json', body: JSON.stringify({ error: 'A roommate just changed the kitchen. It has been refreshed; please try again.' }) })
  })
  await page.getByRole('button', { name: 'Add & split the groceries' }).click()
  await expect(page.getByRole('alert')).toContainText('A roommate just changed the kitchen')
  await expect(page.getByLabel('What did you pick up?')).toHaveValue('Keep this grocery draft')
  await page.unroute('**/api/expenses')
  await page.getByRole('button', { name: 'Add & split the groceries' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.getByText('Keep this grocery draft', { exact: true })).toBeVisible()
})

test('budgets, category filtering, month navigation, and complete ledger export', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Monthly budget', exact: true }).click()
  await page.getByRole('button', { name: 'Edit monthly budget', exact: true }).click()
  await page.getByRole('textbox', { name: 'Monthly budget', exact: true }).fill('100')
  await page.getByRole('button', { name: 'Save the house rules', exact: true }).click()
  await expect(page.locator('.budget-labels')).toContainText('over budget')
  await page.getByRole('button', { name: 'Previous month', exact: true }).click()
  await expect(page.getByRole('meter')).toHaveAttribute('aria-valuenow', '0')
  await page.getByRole('button', { name: 'Next month', exact: true }).click()
  await expect(page.getByRole('meter')).not.toHaveAttribute('aria-valuenow', '0')
  await page.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await page.locator('.category-tabs').getByRole('button', { name: 'Fruit & veg', exact: true }).click()
  await expect(page.locator('.expense-row')).toHaveCount(2)
  await page.getByLabel('Search grocery runs').fill('farmers')
  await expect(page.locator('.expense-row')).toHaveCount(1)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Export ledger', exact: true }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toBe('roomlings-ledger.csv')
  const stream = await download.createReadStream()
  let csv = ''
  for await (const chunk of stream) csv += chunk.toString()
  expect(csv).toContain('The big weekly shop')
  expect(csv).toContain('Farmers market finds')
  expect(csv.split('\r\n')).toHaveLength(7)
})

test('the room offers functional object interactions, lighting, camera controls, and labels', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await expect(page.locator('.world-canvas canvas')).toBeVisible()
  await page.getByRole('button', { name: 'Switch to evening lighting', exact: true }).click()
  await expect(page.locator('.kitchen-world')).toHaveAttribute('data-evening', 'true')
  await page.getByRole('button', { name: 'Switch to daylight', exact: true }).click()
  await expect(page.locator('.kitchen-world')).toHaveAttribute('data-evening', 'false')
  await page.getByRole('button', { name: 'Zoom in', exact: true }).click()
  await expect(page.locator('.world-camera-controls')).toContainText('120%')
  await page.getByRole('button', { name: 'Reset kitchen view', exact: true }).click()
  await expect(page.locator('.world-camera-controls')).toContainText('100%')
  await page.getByRole('button', { name: 'Hide object labels', exact: true }).click()
  await expect(page.locator('.world-hotspots')).toBeHidden()
  await page.getByRole('button', { name: 'Show object labels', exact: true }).click()
  await page.locator('.hotspot-stock').click()
  await expect(page.getByRole('dialog')).toContainText('What is in the bag?')
  await page.keyboard.press('Escape')
  await page.locator('.hotspot-ledger').click()
  await expect(page.getByRole('dialog')).toContainText('The receipt book.')
  await page.keyboard.press('Escape')
  await page.locator('.hotspot-budget').click()
  await expect(page.getByRole('dialog')).toContainText('The little house pot.')
  await page.keyboard.press('Escape')
  await page.locator('.hotspot-roommates').click()
  await expect(page.getByRole('dialog')).toContainText('Your kind of people.')
  await page.keyboard.press('Escape')
  await page.locator('.hotspot-settle').click()
  await expect(page.getByRole('dialog')).toContainText('Keep it even.')
})

test('the ledger remains usable when WebGL is unavailable', async ({ page }) => {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
      value(this: HTMLCanvasElement, contextId: string, options?: unknown) {
        if (contextId.startsWith('webgl')) return null
        return Reflect.apply(original, this, [contextId, options])
      },
    })
  })
  await page.goto('/')
  await expect(page.getByText('Your kitchen, minus the 3D.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.locator('.expense-row')).toHaveCount(6)
})

test('the grocery bag and receipt book meshes work without clickable labels', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await expect(page.locator('.hotspot-stock')).toBeVisible()
  await page.getByRole('button', { name: 'Hide object labels', exact: true }).click()
  await page.mouse.click(655, 474)
  await expect(page.getByRole('dialog')).toContainText('What is in the bag?')
  await page.getByLabel('What did you pick up?').fill('Groceries from the 3D bag')
  await page.getByLabel('Total (EUR)').fill('8.70')
  await page.getByRole('button', { name: 'Add & split the groceries' }).click()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('status')).toContainText('Fridge stocked')
  await page.mouse.click(714, 530)
  await expect(page.getByRole('dialog')).toContainText('The receipt book.')
  await expect(page.getByText('Groceries from the 3D bag', { exact: true })).toBeVisible()
})

test('the kitchen stops drawing behind a finance panel and resumes when it closes', async ({ page }) => {
  await page.addInitScript(() => {
    let draws = 0
    const original = WebGL2RenderingContext.prototype.drawElements
    Object.defineProperty(WebGL2RenderingContext.prototype, 'drawElements', {
      value(this: WebGL2RenderingContext, ...args: Parameters<WebGL2RenderingContext['drawElements']>) {
        draws++
        return Reflect.apply(original, this, args)
      },
    })
    Object.defineProperty(window, 'roomlingsTestDrawCalls', { get: () => draws })
  })
  await page.goto('/')
  const drawCalls = () => page.evaluate(() => Number(Reflect.get(window, 'roomlingsTestDrawCalls')))
  await expect.poll(drawCalls).toBeGreaterThan(0)
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.evaluate(() => new Promise<void>((resolve) => {
    requestAnimationFrame(() => requestAnimationFrame(() => resolve()))
  }))
  const pausedAt = await drawCalls()
  await page.waitForTimeout(250)
  expect(await drawCalls()).toBe(pausedAt)
  await page.keyboard.press('Escape')
  await expect.poll(drawCalls).toBeGreaterThan(pausedAt)
})
