import { accountState, expect, test } from './account-fixtures.ts'

test.use({ reducedMotion: 'reduce' })

test('a new visitor sees the landing without a demo session or an unsolicited sign-in dialog', async ({ page }) => {
  const writes: string[] = []
  page.on('request', (request) => {
    if (new URL(request.url()).pathname.startsWith('/api/') && request.method() !== 'GET') writes.push(request.url())
  })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Share a home.')
  await expect(page.getByRole('status').filter({ hasText: 'Checking saved access' })).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.game-house')).toHaveCount(0)
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  expect(writes).toEqual([])
})

test('the landing carries a new account through sign-in, kitchen creation, return and sign-out', async ({ page, accounts }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  const demos: string[] = []
  page.on('request', (request) => { if (new URL(request.url()).pathname === '/api/demo') demos.push(request.url()) })
  await page.goto('/')
  const start = page.getByRole('link', { name: 'Make yourself at home', exact: true })
  await start.click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Email address', { exact: true }).fill('landing@example.com')
  await dialog.getByRole('button', { name: 'Send sign-in code', exact: true }).click()
  await expect(dialog.getByLabel('Email sign-in code', { exact: true })).toBeVisible()
  await dialog.getByLabel('Email sign-in code', { exact: true }).fill(accounts.provider.codeFor('landing@example.com'))
  await dialog.getByLabel('Account display name', { exact: true }).fill('Robin')
  await dialog.getByLabel('Name this browser', { exact: true }).fill('My phone')
  await dialog.getByRole('button', { name: 'Verify and sign in', exact: true }).click()
  await expect(dialog.getByLabel('What do you call home?', { exact: true })).toBeVisible()
  await dialog.getByLabel('What do you call home?', { exact: true }).fill('A home from the landing')
  await dialog.getByRole('button', { name: 'Create our kitchen', exact: true }).click()
  await dialog.getByRole('button', { name: 'Open A home from the landing', exact: true }).click()
  await expect(page.locator('.game-house')).toContainText('A home from the landing')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  expect(demos).toEqual([])
  expect((await accountState(page)).memberships).toHaveLength(1)
  await page.goto('/')
  await expect(page.locator('.game-house')).toContainText('A home from the landing')
  await expect(page.locator('.welcome')).toHaveCount(0)
  await page.getByRole('button', { name: 'The roommates', exact: true }).click()
  await page.getByRole('button', { name: 'Account and membership', exact: true }).click()
  await dialog.getByRole('button', { name: 'Sign out this device', exact: true }).click()
  await dialog.getByRole('button', { name: 'Sign out this device', exact: true }).click()
  await dialog.getByRole('button', { name: 'Close dialog', exact: true }).click()
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Share a home.')
  await page.reload()
  await expect(page.getByRole('heading', { level: 1 })).toBeVisible()
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.locator('.game-house')).toHaveCount(0)
})

test('closing sign-in restores landing focus and a delivery failure never reports a successful sign-in', async ({ page, accounts }) => {
  accounts.provider.failDelivery = true
  await page.goto('/')
  const signIn = page.getByRole('link', { name: 'Sign in', exact: true })
  await signIn.click()
  const dialog = page.getByRole('dialog')
  await dialog.getByLabel('Email address', { exact: true }).fill('landing@example.com')
  await dialog.getByRole('button', { name: 'Send sign-in code', exact: true }).click()
  await expect(dialog.getByRole('alert')).toContainText('Email delivery is temporarily unavailable.')
  await expect(dialog.getByLabel('Email address', { exact: true })).toHaveValue('landing@example.com')
  await expect(dialog.getByLabel('Email sign-in code', { exact: true })).toHaveCount(0)
  await page.keyboard.press('Escape')
  await expect(dialog).toHaveCount(0)
  await expect(signIn).toBeFocused()
  await expect(signIn).toBeInViewport({ ratio: 1 })
  await signIn.click()
  await expect(dialog.getByLabel('Email address', { exact: true })).toBeVisible()
})

test('an unavailable account service leaves the landing readable and exposes a retry instead of making a sample', async ({ page }) => {
  await page.route('**/api/account', (route) => route.fulfill({ status: 503, json: { error: 'Account access is temporarily unavailable.' } }))
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toContainText('Share a home.')
  await expect(page.getByRole('alert')).toHaveText('Account access is temporarily unavailable.')
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
  await page.unroute('**/api/account')
  await page.getByRole('button', { name: 'Try again', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('link', { name: 'Sign in', exact: true })).toBeVisible()
})
