import { randomUUID } from 'node:crypto'
import type { Page } from '@playwright/test'
import { expect, test } from './account-fixtures.ts'
import { componentCatalog, createRoomComponent, getRoomComponents } from '../../shared/roomComponents.ts'
import { openRoomEditor, openRoomObjects, placeRoomObject } from './fixtures.ts'
import { roomPath } from '../../src/roomNavigation.ts'

test.use({ providerEnabled: false, reducedMotion: 'reduce' })

async function withoutWebGL(page: Page) {
  await page.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext
    Object.defineProperty(HTMLCanvasElement.prototype, 'getContext', {
      value(this: HTMLCanvasElement, type: string, options?: unknown) {
        if (type.startsWith('webgl')) return null
        return Reflect.apply(original, this, [type, options])
      },
    })
  })
}

test('the help button beside Edit room has square dimensions and shared rounded corners', { tag: '@room' }, async ({ page, emptyHousehold: _owner }) => {
  await withoutWebGL(page)
  await page.goto('/kitchen')
  const objects = await openRoomObjects(page)
  const help = objects.getByRole('button', { name: 'How to play', exact: true })
  const edit = objects.getByRole('button', { name: 'Edit room', exact: true })
  for (const width of [1440, 390, 320]) {
    await page.setViewportSize({ width, height: 844 })
    const box = await help.boundingBox()
    expect(box).not.toBeNull()
    expect(Math.abs(box!.width - box!.height)).toBeLessThan(0.1)
    const radius = await edit.evaluate((element) => getComputedStyle(element).borderRadius)
    expect(Number.parseFloat(radius)).toBeGreaterThan(0)
    await expect(help).toHaveCSS('border-radius', radius)
  }
  await help.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
})

test('object info shows only a short description and supplies in live, editor and catalog cards', { tag: '@room' }, async ({ page, emptyHousehold: _owner }) => {
  await withoutWebGL(page)
  await page.goto('/kitchen')
  const objects = await openRoomObjects(page)
  await objects.getByRole('button', { name: 'Info about Fridge', exact: true }).click()
  const liveInfo = objects.getByRole('region', { name: 'Fridge information', exact: true })
  await expect(liveInfo.locator('p')).toHaveText(componentCatalog.fridge.description)
  await expect(liveInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(liveInfo.locator('dd')).toContainText('Surface cleaner')
  await objects.getByRole('button', { name: 'Edit room', exact: true }).click()
  const editor = page.locator('.room-editor')
  const fridgeCard = editor.locator('.room-object-card').filter({ has: page.getByRole('button', { name: 'Edit Fridge', exact: true }) })
  await expect(fridgeCard.locator('.component-preview')).toBeVisible()
  const picture = await fridgeCard.locator('.room-object-picture').boundingBox()
  expect(picture).not.toBeNull()
  await fridgeCard.getByRole('button', { name: 'Info about Fridge', exact: true }).click()
  const fridgeInfo = fridgeCard.getByRole('region', { name: 'Fridge information', exact: true })
  await expect(fridgeInfo).toBeVisible()
  await expect(fridgeCard.locator('.component-preview')).toBeHidden()
  await expect(fridgeInfo.locator('p')).toHaveText(componentCatalog.fridge.description)
  await expect(fridgeInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(fridgeInfo).toContainText('Surface cleaner')
  await expect(fridgeInfo).not.toContainText('Clean the fridge shelves')
  await expect(page.getByRole('tooltip')).toHaveCount(0)
  await expect(page.getByRole('dialog')).toHaveCount(0)
  const information = await fridgeInfo.boundingBox()
  expect(information).not.toBeNull()
  expect(Math.abs(information!.x - picture!.x)).toBeLessThanOrEqual(2)
  expect(Math.abs(information!.y - picture!.y)).toBeLessThanOrEqual(2)
  expect(information!.height).toBeLessThanOrEqual(picture!.height + 1)
  await page.keyboard.press('Escape')
  await expect(fridgeInfo).toHaveCount(0)
  await expect(fridgeCard.getByRole('button', { name: 'Info about Fridge', exact: true })).toBeFocused()

  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  await editor.getByLabel('Find an object', { exact: true }).fill('Dishwasher')
  const dishwasher = editor.getByRole('article', { name: 'Dishwasher', exact: true })
  await dishwasher.getByRole('button', { name: 'Info about Dishwasher', exact: true }).click()
  const dishwasherInfo = dishwasher.getByRole('region', { name: 'Dishwasher information', exact: true })
  await expect(dishwasherInfo).toBeVisible()
  await expect(dishwasher.locator('.component-preview')).toBeHidden()
  await expect(dishwasherInfo.locator('p')).toHaveText(componentCatalog.dishwasher.description)
  await expect(dishwasherInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(dishwasherInfo).not.toContainText('Fitted appliance bay')
  await expect(dishwasherInfo).toContainText('Dishwasher tablets')
  await dishwasher.getByRole('button', { name: 'Preview Dishwasher', exact: true }).focus()
  await page.keyboard.press('Escape')
  await expect(dishwasherInfo).toHaveCount(0)
  await expect(editor).toBeVisible()
  await expect(dishwasher.getByRole('button', { name: 'Info about Dishwasher', exact: true })).toBeFocused()

  await editor.getByLabel('Find an object', { exact: true }).fill('Wall art')
  const wallArt = editor.getByRole('article', { name: 'Wall art', exact: true })
  await wallArt.getByRole('button', { name: 'Info about Wall art', exact: true }).click()
  const wallArtInfo = wallArt.getByRole('region', { name: 'Wall art information', exact: true })
  await expect(wallArtInfo.locator('p')).toHaveText(componentCatalog['wall-art'].description)
  await expect(wallArtInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(wallArtInfo.locator('dd')).toHaveText('No supply shortcuts.')
})

test('catalog preview focuses existing objects without replacing their identity or leaving the catalog', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await page.setViewportSize({ width: 1440, height: 960 })
  const before = await accounts.store.get(owner.household.id)
  await page.goto('/kitchen')
  const editor = await openRoomEditor(page)
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  const panel = page.locator('.room-panel')
  const catalogWidth = await panel.evaluate((element) => element.getBoundingClientRect().width)
  expect(catalogWidth).toBeGreaterThan(1440 * 0.4)
  await editor.getByLabel('Find an object', { exact: true }).fill('Fridge')
  const fridge = editor.getByRole('article', { name: 'Fridge', exact: true })
  const preview = fridge.getByRole('button', { name: 'Preview Fridge', exact: true })
  await expect(preview).toHaveText('Preview')
  await preview.click()
  const world = page.locator('.kitchen-world')
  await expect(world).toHaveAttribute('data-selected-component', 'default-kitchen-fridge')
  await expect(editor.getByRole('button', { name: 'Add objects', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(fridge).toBeVisible()
  await expect.poll(() => panel.evaluate((element) => element.getBoundingClientRect().width)).toBeCloseTo(catalogWidth, 0)
  await expect(page.getByRole('dialog', { name: 'Try Fridge', exact: true })).toHaveCount(0)
  const canvas = world.locator('.world-canvas canvas')
  await expect(canvas).toBeVisible({ timeout: 15_000 })
  await expect(world).toHaveAttribute('data-camera-moving', 'false', { timeout: 15_000 })
  const bounds = await canvas.boundingBox()
  expect(bounds).not.toBeNull()
  const orbit = await canvas.getAttribute('data-camera-orbit')
  await page.mouse.move(bounds!.x + bounds!.width * 0.7, bounds!.y + bounds!.height * 0.75)
  await page.mouse.down()
  await page.mouse.move(bounds!.x + bounds!.width * 0.83, bounds!.y + bounds!.height * 0.75, { steps: 8 })
  await page.mouse.up()
  await expect(canvas).not.toHaveAttribute('data-camera-orbit', orbit!)
  await expect(world).toHaveAttribute('data-selected-component', 'default-kitchen-fridge')
  await expect(editor.getByRole('button', { name: 'Add objects', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect.poll(() => panel.evaluate((element) => element.getBoundingClientRect().width)).toBeCloseTo(catalogWidth, 0)
  expect(await accounts.store.get(owner.household.id)).toEqual(before)
})

test('a blocked catalog preview never changes the saved room or the existing private draft', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await withoutWebGL(page)
  const before = await accounts.store.get(owner.household.id)
  await page.goto(roomPath('living-room'))
  const editor = await openRoomEditor(page)
  await editor.getByRole('button', { name: 'Edit Sofa', exact: true }).click()
  await editor.getByLabel('Object name', { exact: true }).fill('Keep this sofa draft')
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  await editor.getByLabel('Find an object', { exact: true }).fill('Tea set')
  const tea = editor.getByRole('article', { name: 'Tea set', exact: true })
  await expect(tea).toHaveAttribute('data-availability', 'occupied')
  const warning = tea.locator('.room-availability')
  await expect(warning).toHaveRole('img')
  await expect(warning).toHaveAccessibleName('Make room first')
  await expect(warning).toHaveText('')
  await expect(warning.locator('svg.lucide-triangle-alert')).toHaveCount(1)
  await expect(warning).toHaveCSS('width', '22px')
  await expect(warning).toHaveCSS('height', '22px')
  const preview = tea.getByRole('button', { name: 'Preview Tea set', exact: true })
  await expect(preview).toBeEnabled()
  await expect(preview).toHaveText('Preview')
  await expect(tea.getByRole('button', { name: /^Review / })).toHaveCount(0)
  await tea.getByRole('button', { name: 'Info about Tea set', exact: true }).click()
  const teaInfo = tea.getByRole('region', { name: 'Tea set information', exact: true })
  await expect(teaInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(teaInfo).not.toContainText('Occupied by Board game')
  await preview.click()
  const trial = page.getByRole('dialog', { name: 'Try Tea set', exact: true })
  await expect(trial.getByRole('button', { name: 'Place object', exact: true })).toBeDisabled()
  await expect(trial.getByText('Occupied by Board game.', { exact: true })).toBeVisible()
  await expect(trial).not.toContainText('Table 1 of 1')
  await expect(trial).not.toContainText('This preview does not change your room or draft.')
  expect((await accounts.store.get(owner.household.id))?.roomComponents).toEqual(before?.roomComponents)
  await trial.getByRole('button', { name: 'Discard preview', exact: true }).click()
  await expect(editor.locator('.room-editor-notice')).toHaveCount(0)
  await expect(preview).toBeFocused()
  await expect(editor.locator('.room-editor-footer').getByRole('status')).toHaveText('1 object has unapplied changes.')
  await editor.getByRole('button', { name: /^In this room/ }).click()
  await editor.getByRole('button', { name: 'Edit Keep this sofa draft', exact: true }).click()
  await expect(editor.getByLabel('Object name', { exact: true })).toHaveValue('Keep this sofa draft')
  expect((await accounts.store.get(owner.household.id))?.roomComponents).toEqual(before?.roomComponents)
})

test('a full-zone catalog inspection keeps an accepted placement draft private and unchanged', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await withoutWebGL(page)
  const household = await accounts.store.get(owner.household.id)
  if (!household) throw new Error('The isolated household is missing.')
  household.roomComponents = [...getRoomComponents(household), ...([
    ['air-fryer', 'kitchen-air-fryer'], ['stand-mixer', 'kitchen-stand-mixer'], ['blender', 'kitchen-blender'],
    ['paper-towel-holder', 'kitchen-paper-towels'], ['cutting-boards', 'kitchen-cutting-boards'],
  ] as const).map(([kind, slot]) => createRoomComponent(kind, slot, randomUUID()))]
  await accounts.store.save(household)
  const before = await accounts.store.get(owner.household.id)
  await page.goto('/kitchen')
  const editor = await openRoomEditor(page)
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  await editor.getByLabel('Find an object', { exact: true }).fill('Dishwasher')
  await placeRoomObject(editor, 'Dishwasher')
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  await editor.getByLabel('Find an object', { exact: true }).fill('Coffee machine')
  const coffee = editor.getByRole('article', { name: 'Coffee machine', exact: true })
  await expect(coffee).toHaveAttribute('data-availability', 'occupied')
  const preview = coffee.getByRole('button', { name: 'Preview Coffee machine', exact: true })
  await expect(preview).toBeEnabled()
  await expect(preview).toHaveText('Preview')
  await expect(coffee.getByRole('button', { name: /^Review / })).toHaveCount(0)
  await coffee.getByRole('button', { name: 'Info about Coffee machine', exact: true }).click()
  const coffeeInfo = coffee.getByRole('region', { name: 'Coffee machine information', exact: true })
  await expect(coffeeInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(coffeeInfo).not.toContainText('Make room first')
  await preview.click()
  const trial = page.getByRole('dialog', { name: 'Try Coffee machine', exact: true })
  await expect(trial.getByRole('button', { name: 'Place object', exact: true })).toBeDisabled()
  await expect(trial).toContainText('Make room first')
  await expect(trial).not.toContainText('This preview does not change your room or draft.')
  await expect(editor).toHaveAttribute('data-pending-count', '1')
  expect(await accounts.store.get(owner.household.id)).toEqual(before)
  await trial.getByRole('button', { name: 'Discard preview', exact: true }).click()
  await expect(editor.locator('.room-editor-notice')).toHaveCount(0)
  await expect(preview).toBeFocused()
  await expect(editor.locator('.room-editor-footer').getByRole('status')).toHaveText('1 object has unapplied changes.')
  await editor.getByRole('button', { name: /^In this room/ }).click()
  await editor.getByRole('button', { name: 'Edit Dishwasher', exact: true }).click()
  await expect(editor.getByLabel('Object name', { exact: true })).toHaveValue('Dishwasher')
  expect(await accounts.store.get(owner.household.id)).toEqual(before)
})

test('an occupied catalog slot still renders the inspected object without allowing it to be placed', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }, testInfo) => {
  const before = await accounts.store.get(owner.household.id)
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto(roomPath('living-room'))
  const world = page.locator('.living-room-world')
  await expect(world.locator('.world-canvas canvas')).toBeVisible({ timeout: 30_000 })
  const editor = await openRoomEditor(page)
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  const tea = editor.getByRole('article', { name: 'Tea set', exact: true })
  const preview = tea.getByRole('button', { name: 'Preview Tea set', exact: true })
  await preview.click()
  const trial = page.getByRole('dialog', { name: 'Try Tea set', exact: true })
  const id = await editor.getAttribute('data-placement-preview')
  if (!id) throw new Error('The inspected object has no preview identifier.')
  expect(getRoomComponents(before ?? {}).map((component) => component.id)).not.toContain(id)
  await expect(editor).toHaveAttribute('data-inspection-preview', 'true')
  await expect(trial.getByRole('button', { name: 'Place object', exact: true })).toBeDisabled()
  await expect(world.locator('canvas')).toHaveAttribute('data-placement-arrow', 'true')
  await expect(world).toHaveAttribute('data-selected-component', id)
  await expect(world.locator('.world-hotspot')).toHaveCount(0)
  expect(await accounts.store.get(owner.household.id)).toEqual(before)
  await page.screenshot({ path: testInfo.outputPath('occupied-tea-set-inspection.png'), animations: 'disabled' })
  await trial.getByRole('button', { name: 'Discard preview', exact: true }).click()
  await expect(world.locator('canvas')).toHaveAttribute('data-placement-arrow', 'false')
  await expect(editor.locator('.room-editor-notice')).toHaveCount(0)
  await expect(editor.locator('.room-editor-footer').getByRole('status')).toHaveText('No unapplied changes.')
  await expect(preview).toBeFocused()
  expect(await accounts.store.get(owner.household.id)).toEqual(before)
})

test('previewing a stored copy restores that identity instead of focusing another placed copy', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await withoutWebGL(page)
  const household = await accounts.store.get(owner.household.id)
  if (!household) throw new Error('The isolated household is missing.')
  const installed = getRoomComponents(household).filter((component) => component.roomId === 'kitchen' && component.kind === 'plant' && component.installed)
  expect(installed.length).toBeGreaterThan(0)
  const stored = { ...createRoomComponent('plant', 'kitchen-table-center', randomUUID()), installed: false, name: 'Our stored plant' }
  household.roomComponents = [...getRoomComponents(household), stored]
  await accounts.store.save(household)
  const before = await accounts.store.get(owner.household.id)
  await page.goto('/kitchen')
  const editor = await openRoomEditor(page)
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  const plant = editor.getByRole('article', { name: 'Plant', exact: true })
  const preview = plant.getByRole('button', { name: 'Preview Plant', exact: true })
  await expect(preview).toHaveText('Preview')
  await preview.click()
  await expect(editor).toHaveAttribute('data-placement-preview', stored.id)
  await expect(page.locator('.kitchen-world')).toHaveAttribute('data-selected-component', stored.id)
  const trial = page.getByRole('dialog', { name: 'Try Our stored plant', exact: true })
  await expect(trial.getByRole('button', { name: 'Place object', exact: true })).toBeEnabled()
  await trial.getByRole('button', { name: 'Place object', exact: true }).click()
  expect(await accounts.store.get(owner.household.id)).toEqual(before)
  await editor.getByRole('button', { name: 'Apply for everyone', exact: true }).click()
  await expect(editor).toHaveCount(0)
  const saved = await accounts.store.get(owner.household.id)
  expect(saved?.roomComponents?.find((component) => component.id === stored.id)).toMatchObject({
    name: stored.name, slotId: stored.slotId, installed: true,
  })
  for (const component of installed) expect(saved?.roomComponents?.find((saved) => saved.id === component.id)).toEqual(component)
})

test('long inline object information scrolls without changing the card size or trapping Escape', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await withoutWebGL(page)
  const household = await accounts.store.get(owner.household.id)
  if (!household) throw new Error('The isolated household is missing.')
  household.roomComponents = getRoomComponents(household).map((component) => component.kind === 'fridge' ? {
    ...component, supplies: Array.from({ length: 12 }, (_, index) => ({
      id: `cleaner-${index}`, name: `A carefully labelled cleaning supply ${index + 1}`, quantity: '2 replacement bottles',
    })),
  } : component)
  await accounts.store.save(household)
  await page.setViewportSize({ width: 320, height: 568 })
  await page.goto('/kitchen')
  const editor = await openRoomEditor(page)
  const card = editor.locator('.room-object-card').filter({ has: page.getByRole('button', { name: 'Edit Fridge', exact: true }) })
  await card.scrollIntoViewIfNeeded()
  const before = await card.boundingBox()
  await card.getByRole('button', { name: 'Info about Fridge', exact: true }).click()
  const information = card.getByRole('region', { name: 'Fridge information', exact: true })
  await expect(information).toBeVisible()
  await expect(information.locator('dt')).toHaveText(['Supplies'])
  await expect(information.locator('dd')).toContainText('2 replacement bottles A carefully labelled cleaning supply 12')
  expect((await card.boundingBox())!.height).toBeCloseTo(before!.height, 1)
  expect(await information.evaluate((element) => element.scrollHeight > element.clientHeight)).toBe(true)
  await information.focus()
  await page.keyboard.press('End')
  await expect.poll(() => information.evaluate((element) => element.scrollTop)).toBeGreaterThan(0)
  await page.keyboard.press('Escape')
  await expect(information).toHaveCount(0)
  await expect(editor).toBeVisible()
  await expect(card.getByRole('button', { name: 'Info about Fridge', exact: true })).toBeFocused()
  await expect(editor.locator('button button')).toHaveCount(0)
  expect((await accounts.store.get(owner.household.id))?.roomComponents).toEqual(household.roomComponents)
})

test('retired objects stay editable and storable but cannot be added, moved or restored', { tag: '@room' }, async ({ page, accounts, emptyHousehold: owner }) => {
  await withoutWebGL(page)
  const household = await accounts.store.get(owner.household.id)
  if (!household) throw new Error('The isolated household is missing.')
  const speaker = createRoomComponent('speaker', 'living-room-media-accessory', randomUUID())
  household.roomComponents = [...getRoomComponents(household), speaker]
  await accounts.store.save(household)

  await page.goto(roomPath('living-room'))
  const objects = await openRoomObjects(page)
  await objects.getByRole('button', { name: 'Open Speaker details', exact: true }).click()
  await objects.getByRole('button', { name: 'Edit this object', exact: true }).click()
  const editor = page.locator('.room-editor')
  await expect(editor).toContainText('This object is no longer offered in Add objects')
  await expect(editor.getByRole('combobox', { name: 'Move object', exact: true })).toHaveCount(0)
  await editor.getByRole('button', { name: 'Add objects', exact: true }).click()
  await editor.getByLabel('Find an object', { exact: true }).fill('Speaker')
  await expect(editor.getByRole('article', { name: 'Speaker', exact: true })).toHaveCount(0)
  await editor.getByLabel('Find an object', { exact: true }).fill('Wall art')
  await expect(editor.getByRole('article', { name: 'Wall art', exact: true })).toBeVisible()
  await editor.getByRole('button', { name: /^In this room/ }).click()
  await editor.getByRole('button', { name: 'Edit Speaker', exact: true }).click()
  await editor.getByLabel('Object name', { exact: true }).fill('Stored speaker')
  await editor.getByRole('button', { name: 'Put in storage', exact: true }).click()
  await editor.getByRole('button', { name: 'Storage', exact: true }).click()
  const stored = editor.locator(`[data-stored-component="${speaker.id}"]`)
  await expect(stored.getByRole('button', { name: 'Edit stored Stored speaker', exact: true })).toBeVisible()
  await expect(stored.getByRole('button', { name: /^Bring back / })).toHaveCount(0)
  await stored.getByRole('button', { name: 'Info about Stored speaker', exact: true }).click()
  const storedInfo = stored.getByRole('region', { name: 'Stored speaker information', exact: true })
  await expect(storedInfo.locator('p')).toHaveText(componentCatalog.speaker.description)
  await expect(storedInfo.locator('dt')).toHaveText(['Supplies'])
  await expect(storedInfo).not.toContainText('cannot be moved or brought back')
  expect((await accounts.store.get(owner.household.id))?.roomComponents).toEqual(household.roomComponents)
  await editor.getByRole('button', { name: 'Apply for everyone', exact: true }).click()
  await expect(editor).toHaveCount(0)
  const saved = (await accounts.store.get(owner.household.id))?.roomComponents?.find((component) => component.id === speaker.id)
  expect(saved).toMatchObject({ id: speaker.id, kind: speaker.kind, slotId: speaker.slotId, name: 'Stored speaker', installed: false })
  expect(saved?.supplies).toEqual(speaker.supplies)
})
