import { expect, test } from '@playwright/test'

test.use({ reducedMotion: 'reduce' })

test('Georgia titles and system body fonts apply throughout while inputs remain responsive', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 960 })
  await page.goto('/')
  await expect(page.getByRole('heading', { level: 1 })).toHaveCSS('font-family', /Georgia/)
  await expect(page.locator('.welcome-hero-copy > p').first()).toHaveCSS('font-family', /system-ui/)
  await expect(page.locator('.welcome-feature h3').first()).toHaveCSS('font-family', /Georgia/)
  await page.goto('/sample/kitchen')
  await page.getByRole('button', { name: 'Grocery runs', exact: true }).click()
  await page.evaluate(() => document.fonts.ready)
  const heading = page.locator('.room-panel-header h2')
  await expect(heading).toHaveCSS('font-family', /Georgia/)
  await expect(heading).toHaveCSS('font-size', '27px')
  await expect(page.locator('.room-panel-subtitle')).toHaveCSS('font-size', '12px')
  await expect(page.locator('.expense-description strong').first()).toHaveCSS('font-size', '12px')
  const exportButton = page.getByRole('button', { name: 'Export ledger', exact: true })
  await expect(exportButton).toHaveCSS('font-family', /system-ui/)
  await expect(exportButton).toHaveCSS('font-size', '11px')
  await page.getByRole('button', { name: 'Close panel', exact: true }).click()
  await page.getByRole('button', { name: 'House rules', exact: true }).click()
  await expect(page.getByLabel('Kitchen name', { exact: true })).toHaveCSS('font-size', '13px')
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByLabel('Kitchen name', { exact: true })).toHaveCSS('font-size', '16px')
  const save = page.getByRole('button', { name: 'Save the house rules', exact: true })
  expect(await save.evaluate((element) => element.getBoundingClientRect().height)).toBeGreaterThanOrEqual(44)
  await expect(page.getByRole('dialog').getByRole('heading', { level: 2 })).toHaveCSS('font-family', /Georgia/)
})
