// Generated by design/roomlings-logo/prepare_assets.py.
export const brandDimensions = {
  "icon": {
    "width": 256,
    "height": 256
  },
  "wordmark": {
    "width": 4252.0,
    "height": 939
  }
} as const
